language: php
sudo: false

php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'

before_script:
  - printf "\n \n \n \n \n" | pecl install swoole
  - composer update

script:
  - ./vendor/bin/parallel-lint src
  - ./vendor/bin/phpcs --standard=PSR2 -n src
